/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-05-22 18:54:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import model.*;
import dao.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("dao");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    List<Course> courses = (List<Course>) request.getAttribute("courses");
    List<Student> students = (List<Student>) request.getAttribute("students");
    List<Enrollment> report = (List<Enrollment>) request.getAttribute("report");
    CourseDAO courseDAO = new CourseDAO();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <meta name=\"description\" content=\"Administrative control panel for Course Registration System. Manage courses, student profiles, and view registration reports.\">\n");
      out.write("  <title>Course Hub – Admin Dashboard</title>\n");
      out.write("  <!-- Google Fonts Outfit -->\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <!-- Navigation Header -->\n");
      out.write("  <header>\n");
      out.write("    <nav class=\"navbar\" id=\"admin-nav\">\n");
      out.write("      <div class=\"nav-container\">\n");
      out.write("        <span class=\"brand\">🎓 Admin Control Panel</span>\n");
      out.write("        <div class=\"nav-user-area\">\n");
      out.write("          <span class=\"user-welcome\">Active Session: <strong>Administrator</strong></span>\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"btn btn-sm btn-logout\" id=\"nav-btn-logout\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <main class=\"container\">\n");
      out.write("    <section class=\"dashboard-hero admin-hero\">\n");
      out.write("      <div class=\"hero-content\">\n");
      out.write("        <h1>Administrative Dashboard</h1>\n");
      out.write("        <p>Manage curriculum course lists, view registered student records, and generate real-time enrollment audit reports.</p>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Stats Dashboard Row -->\n");
      out.write("    <section class=\"stats-row\" id=\"stats-dashboard\">\n");
      out.write("      <div class=\"stat-card\" id=\"stat-courses\">\n");
      out.write("        <div class=\"stat-icon-wrapper courses-icon\">📚</div>\n");
      out.write("        <div class=\"stat-content\">\n");
      out.write("          <h2>");
      out.print( courses != null ? courses.size() : 0 );
      out.write("</h2>\n");
      out.write("          <p>Active Courses</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"stat-card\" id=\"stat-students\">\n");
      out.write("        <div class=\"stat-icon-wrapper students-icon\">👤</div>\n");
      out.write("        <div class=\"stat-content\">\n");
      out.write("          <h2>");
      out.print( students != null ? students.size() : 0 );
      out.write("</h2>\n");
      out.write("          <p>Registered Students</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("      <div class=\"stat-card\" id=\"stat-enrollments\">\n");
      out.write("        <div class=\"stat-icon-wrapper enrollments-icon\">📊</div>\n");
      out.write("        <div class=\"stat-content\">\n");
      out.write("          <h2>");
      out.print( report != null ? report.size() : 0 );
      out.write("</h2>\n");
      out.write("          <p>Total Enrollments</p>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Form & Lists Grid -->\n");
      out.write("    <div class=\"admin-workspace-grid\">\n");
      out.write("      \n");
      out.write("      <!-- Create Course Card -->\n");
      out.write("      <section class=\"card form-card\" id=\"section-add-course\">\n");
      out.write("        <h2>Add New Course</h2>\n");
      out.write("        <p class=\"section-intro\">Define course attributes and capacity limits to create a curriculum module.</p>\n");
      out.write("        \n");
      out.write("        <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" method=\"post\" id=\"add-course-form\">\n");
      out.write("          <input type=\"hidden\" name=\"action\" value=\"addCourse\"/>\n");
      out.write("          \n");
      out.write("          <div class=\"form-grid-row\">\n");
      out.write("            <div class=\"form-group flex-2\">\n");
      out.write("              <label for=\"courseName\">Course Name</label>\n");
      out.write("              <input type=\"text\" id=\"courseName\" name=\"courseName\" class=\"form-control\" placeholder=\"e.g. Advanced Java Concepts\" required/>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group flex-1\">\n");
      out.write("              <label for=\"instructor\">Instructor</label>\n");
      out.write("              <input type=\"text\" id=\"instructor\" name=\"instructor\" class=\"form-control\" placeholder=\"e.g. Dr. Jenkins\" required/>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-grid-row\">\n");
      out.write("            <div class=\"form-group flex-2\">\n");
      out.write("              <label for=\"schedule\">Weekly Schedule</label>\n");
      out.write("              <input type=\"text\" id=\"schedule\" name=\"schedule\" class=\"form-control\" placeholder=\"e.g. Mon/Wed 09:00 AM - 11:00 AM\" required/>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <div class=\"form-group flex-1\">\n");
      out.write("              <label for=\"credits\">Credits</label>\n");
      out.write("              <input type=\"number\" id=\"credits\" name=\"credits\" class=\"form-control\" min=\"1\" max=\"6\" value=\"3\" required/>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"form-group flex-1\">\n");
      out.write("              <label for=\"capacity\">Student Capacity</label>\n");
      out.write("              <input type=\"number\" id=\"capacity\" name=\"capacity\" class=\"form-control\" min=\"1\" max=\"100\" value=\"30\" required/>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"form-group\">\n");
      out.write("            <label for=\"description\">Course Description</label>\n");
      out.write("            <textarea id=\"description\" name=\"description\" class=\"form-control\" placeholder=\"Provide a brief course outline...\" rows=\"3\" required></textarea>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <button type=\"submit\" class=\"btn btn-primary\" id=\"btn-add-course\">Create Course Module</button>\n");
      out.write("        </form>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <!-- Manage Courses Card -->\n");
      out.write("      <section class=\"card table-card\" id=\"section-manage-courses\">\n");
      out.write("        <h2>Manage Active Courses</h2>\n");
      out.write("        <div class=\"table-wrapper\">\n");
      out.write("          <table class=\"table\" id=\"courses-table\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>ID</th>\n");
      out.write("                <th>Course Name</th>\n");
      out.write("                <th>Instructor</th>\n");
      out.write("                <th>Credits</th>\n");
      out.write("                <th>Capacity</th>\n");
      out.write("                <th>Enrolled</th>\n");
      out.write("                <th>Action</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              ");
 
                if(courses != null && !courses.isEmpty()) {
                  for(Course c : courses) {
                    int enrolled = courseDAO.getEnrolledCount(c.getId());
                    boolean isFull = enrolled >= c.getCapacity();
              
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td><code>");
      out.print( c.getId() );
      out.write("</code></td>\n");
      out.write("                  <td><strong>");
      out.print( c.getCourseName() );
      out.write("</strong></td>\n");
      out.write("                  <td>");
      out.print( c.getInstructor() );
      out.write("</td>\n");
      out.write("                  <td>");
      out.print( c.getCredits() );
      out.write(" Units</td>\n");
      out.write("                  <td>");
      out.print( c.getCapacity() );
      out.write("</td>\n");
      out.write("                  <td>\n");
      out.write("                    <span class=\"badge ");
      out.print( isFull ? "badge-danger" : "badge-success" );
      out.write("\">\n");
      out.write("                      ");
      out.print( enrolled );
      out.write("\n");
      out.write("                    </span>\n");
      out.write("                  </td>\n");
      out.write("                  <td>\n");
      out.write("                    <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" class=\"action-inline-form\">\n");
      out.write("                      <input type=\"hidden\" name=\"action\" value=\"deleteCourse\"/>\n");
      out.write("                      <input type=\"hidden\" name=\"courseId\" value=\"");
      out.print( c.getId() );
      out.write("\"/>\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-danger btn-sm\" id=\"btn-delete-course-");
      out.print( c.getId() );
      out.write("\" onclick=\"return confirm('Confirm deletion of this course? This deletes associated enrollments.')\">\n");
      out.write("                        Delete\n");
      out.write("                      </button>\n");
      out.write("                    </form>\n");
      out.write("                  </td>\n");
      out.write("                </tr>\n");
      out.write("              ");
 
                  }
                } else {
              
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td colspan=\"7\" class=\"empty-table-cell\">No active courses. Use the form above to add a course.</td>\n");
      out.write("                </tr>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <!-- Manage Students Card -->\n");
      out.write("      <section class=\"card table-card\" id=\"section-manage-students\">\n");
      out.write("        <h2>Manage Registered Students</h2>\n");
      out.write("        <div class=\"table-wrapper\">\n");
      out.write("          <table class=\"table\" id=\"students-table\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>Student ID</th>\n");
      out.write("                <th>Full Name</th>\n");
      out.write("                <th>Email Address</th>\n");
      out.write("                <th>Action</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              ");
 
                if(students != null && !students.isEmpty()) {
                  for(Student s : students) {
              
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td><code>");
      out.print( s.getId() );
      out.write("</code></td>\n");
      out.write("                  <td><strong>");
      out.print( s.getName() );
      out.write("</strong></td>\n");
      out.write("                  <td>");
      out.print( s.getEmail() );
      out.write("</td>\n");
      out.write("                  <td>\n");
      out.write("                    <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashboard\" class=\"action-inline-form\">\n");
      out.write("                      <input type=\"hidden\" name=\"action\" value=\"deleteStudent\"/>\n");
      out.write("                      <input type=\"hidden\" name=\"studentId\" value=\"");
      out.print( s.getId() );
      out.write("\"/>\n");
      out.write("                      <button type=\"submit\" class=\"btn btn-danger btn-sm\" id=\"btn-delete-student-");
      out.print( s.getId() );
      out.write("\" onclick=\"return confirm('Confirm deletion of student ");
      out.print( s.getName() );
      out.write("? All their enrollments will be deleted.')\">\n");
      out.write("                        Delete Student\n");
      out.write("                      </button>\n");
      out.write("                    </form>\n");
      out.write("                  </td>\n");
      out.write("                </tr>\n");
      out.write("              ");
 
                  }
                } else {
              
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td colspan=\"4\" class=\"empty-table-cell\">No students registered in the portal.</td>\n");
      out.write("                </tr>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <!-- Enrollment Report Card -->\n");
      out.write("      <section class=\"card table-card\" id=\"section-enrollment-report\">\n");
      out.write("        <h2>📊 Real-Time Enrollment Report</h2>\n");
      out.write("        <p class=\"section-intro\">JDBC generated registration audit report detailing student course associations.</p>\n");
      out.write("        \n");
      out.write("        <div class=\"table-wrapper\">\n");
      out.write("          <table class=\"table\" id=\"report-table\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>#</th>\n");
      out.write("                <th>Student</th>\n");
      out.write("                <th>Course Name</th>\n");
      out.write("                <th>Enrolled On</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              ");
 
                if(report != null && !report.isEmpty()) {
                  int index = 1;
                  for(Enrollment e : report) {
              
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td>");
      out.print( index++ );
      out.write("</td>\n");
      out.write("                  <td><strong>");
      out.print( e.getStudentName() );
      out.write("</strong></td>\n");
      out.write("                  <td>");
      out.print( e.getCourseName() );
      out.write("</td>\n");
      out.write("                  <td><span class=\"report-timestamp\">");
      out.print( e.getEnrolledAt() );
      out.write("</span></td>\n");
      out.write("                </tr>\n");
      out.write("              ");
 
                  }
                } else {
              
      out.write("\n");
      out.write("                <tr>\n");
      out.write("                  <td colspan=\"4\" class=\"empty-table-cell\">No active enrollments recorded in the database.</td>\n");
      out.write("                </tr>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
