/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.55
 * Generated at: 2026-05-22 18:55:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.student;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.*;
import model.*;
import dao.*;

public final class courses_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(8);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("dao");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

    Student student = (Student) session.getAttribute("student");
    List<Course> courses = (List<Course>) request.getAttribute("courses");
    Set<Integer> enrolledIds = (Set<Integer>) request.getAttribute("enrolledIds");
    List<Enrollment> myEnrollments = (List<Enrollment>) request.getAttribute("myEnrollments");
    CourseDAO courseDAO = new CourseDAO();

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("  <meta name=\"description\" content=\"View available courses and manage your registrations in the student course registration portal.\">\n");
      out.write("  <title>Course Hub – Student Portal</title>\n");
      out.write("  <!-- Google Fonts Outfit -->\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\n");
      out.write("  <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <!-- Semantic Header -->\n");
      out.write("  <header>\n");
      out.write("    <nav class=\"navbar\" id=\"student-nav\">\n");
      out.write("      <div class=\"nav-container\">\n");
      out.write("        <span class=\"brand\">🎓 CourseHub</span>\n");
      out.write("        <div class=\"nav-user-area\">\n");
      out.write("          <span class=\"user-welcome\">Welcome, <strong>");
      out.print( student.getName() );
      out.write("</strong></span>\n");
      out.write("          <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout\" class=\"btn btn-sm btn-logout\" id=\"nav-btn-logout\">Logout</a>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("  </header>\n");
      out.write("\n");
      out.write("  <main class=\"container\">\n");
      out.write("    <!-- Hero Dashboard Intro -->\n");
      out.write("    <section class=\"dashboard-hero\">\n");
      out.write("      <div class=\"hero-content\">\n");
      out.write("        <h1>Explore Available Courses</h1>\n");
      out.write("        <p>Enroll in standard modules, review instructors, schedules, and monitor real-time class capacities.</p>\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("    <!-- Feedback messages -->\n");
      out.write("    ");
 String msg = request.getParameter("msg"); 
      out.write("\n");
      out.write("    ");
 if("success".equals(msg)) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-success\" id=\"alert-enroll-success\" role=\"alert\">\n");
      out.write("        <span class=\"alert-icon\">✨</span> Enrolled in course successfully!\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if("dropped".equals(msg)) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-info\" id=\"alert-enroll-drop\" role=\"alert\">\n");
      out.write("        <span class=\"alert-icon\">ℹ️</span> Course dropped from schedule.\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("    ");
 if("failed".equals(msg)) { 
      out.write("\n");
      out.write("      <div class=\"alert alert-error\" id=\"alert-enroll-failed\" role=\"alert\">\n");
      out.write("        <span class=\"alert-icon\">⚠️</span> Action failed: Course is full or you are already enrolled.\n");
      out.write("      </div>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"dashboard-grid\">\n");
      out.write("      <!-- Left Column: Available Courses -->\n");
      out.write("      <section class=\"main-content-col\">\n");
      out.write("        <div class=\"section-header\">\n");
      out.write("          <h2>Active Course Offerings</h2>\n");
      out.write("          <span class=\"count-badge\">");
      out.print( courses != null ? courses.size() : 0 );
      out.write(" courses available</span>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"course-grid\">\n");
      out.write("        ");
 
           if (courses != null) {
             for(Course c : courses) {
               int enrolled = courseDAO.getEnrolledCount(c.getId());
               boolean isFull = enrolled >= c.getCapacity();
               boolean isEnrolled = enrolledIds != null && enrolledIds.contains(c.getId());
               double fillPercentage = ((double) enrolled / c.getCapacity()) * 100;
        
      out.write("\n");
      out.write("          <article class=\"course-card ");
      out.print( isEnrolled ? "enrolled-card" : "" );
      out.write("\" id=\"course-");
      out.print( c.getId() );
      out.write("\">\n");
      out.write("            <div class=\"course-card-header\">\n");
      out.write("              <h3>");
      out.print( c.getCourseName() );
      out.write("</h3>\n");
      out.write("              <div class=\"badges-row\">\n");
      out.write("                ");
 if(isEnrolled) { 
      out.write("\n");
      out.write("                  <span class=\"badge badge-success\">Enrolled</span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("                ");
 if(isFull && !isEnrolled) { 
      out.write("\n");
      out.write("                  <span class=\"badge badge-danger\">Class Full</span>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            <p class=\"course-desc\">");
      out.print( c.getDescription() );
      out.write("</p>\n");
      out.write("            \n");
      out.write("            <div class=\"course-meta\">\n");
      out.write("              <div class=\"meta-item\">\n");
      out.write("                <span class=\"meta-icon\" aria-hidden=\"true\">👤</span>\n");
      out.write("                <span class=\"meta-text\"><strong>Instructor:</strong> ");
      out.print( c.getInstructor() );
      out.write("</span>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"meta-item\">\n");
      out.write("                <span class=\"meta-icon\" aria-hidden=\"true\">📅</span>\n");
      out.write("                <span class=\"meta-text\"><strong>Schedule:</strong> ");
      out.print( c.getSchedule() );
      out.write("</span>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"meta-item\">\n");
      out.write("                <span class=\"meta-icon\" aria-hidden=\"true\">📚</span>\n");
      out.write("                <span class=\"meta-text\"><strong>Credits:</strong> ");
      out.print( c.getCredits() );
      out.write(" Units</span>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"meta-item\">\n");
      out.write("                <span class=\"meta-icon\" aria-hidden=\"true\">👥</span>\n");
      out.write("                <span class=\"meta-text\"><strong>Class Size:</strong> ");
      out.print( enrolled );
      out.write(' ');
      out.write('/');
      out.write(' ');
      out.print( c.getCapacity() );
      out.write("</span>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <!-- Capacity Progress Bar -->\n");
      out.write("            <div class=\"capacity-progress-wrapper\" aria-label=\"Course capacity progress\">\n");
      out.write("              <div class=\"capacity-progress-bar\">\n");
      out.write("                <div class=\"progress-fill ");
      out.print( fillPercentage >= 100 ? "progress-full" : (fillPercentage >= 80 ? "progress-warning" : "") );
      out.write("\" \n");
      out.write("                     style=\"width: ");
      out.print( fillPercentage );
      out.write("%;\"></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"course-actions\">\n");
      out.write("              <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/student/enroll\" method=\"post\">\n");
      out.write("                <input type=\"hidden\" name=\"courseId\" value=\"");
      out.print( c.getId() );
      out.write("\"/>\n");
      out.write("                ");
 if(isEnrolled) { 
      out.write("\n");
      out.write("                  <input type=\"hidden\" name=\"action\" value=\"drop\"/>\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-danger btn-block btn-sm\" id=\"btn-drop-");
      out.print( c.getId() );
      out.write("\">\n");
      out.write("                    Drop Course\n");
      out.write("                  </button>\n");
      out.write("                ");
 } else if(!isFull) { 
      out.write("\n");
      out.write("                  <input type=\"hidden\" name=\"action\" value=\"enroll\"/>\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary btn-block btn-sm\" id=\"btn-enroll-");
      out.print( c.getId() );
      out.write("\">\n");
      out.write("                    Register Course\n");
      out.write("                  </button>\n");
      out.write("                ");
 } else { 
      out.write("\n");
      out.write("                  <button type=\"button\" disabled class=\"btn btn-disabled btn-block btn-sm\" id=\"btn-full-");
      out.print( c.getId() );
      out.write("\">\n");
      out.write("                    Course Full\n");
      out.write("                  </button>\n");
      out.write("                ");
 } 
      out.write("\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </article>\n");
      out.write("        ");
 
             } 
           } 
        
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </section>\n");
      out.write("\n");
      out.write("      <!-- Right Column: My Schedule Summary -->\n");
      out.write("      <aside class=\"sidebar-col\">\n");
      out.write("        <div class=\"card my-schedule-card\">\n");
      out.write("          <h2>My Active Schedule</h2>\n");
      out.write("          <p class=\"sidebar-intro\">Review your current registrations and semester load.</p>\n");
      out.write("\n");
      out.write("          ");
 if(myEnrollments != null && !myEnrollments.isEmpty()) { 
      out.write("\n");
      out.write("            <div class=\"schedule-summary-stat\">\n");
      out.write("              ");
 
                int totalCredits = 0;
                for(Enrollment e : myEnrollments) {
                    Course c = courseDAO.getCourseById(e.getCourseId());
                    if(c != null) {
                        totalCredits += c.getCredits();
                    }
                }
              
      out.write("\n");
      out.write("              <div class=\"stat-number\">");
      out.print( myEnrollments.size() );
      out.write("</div>\n");
      out.write("              <div class=\"stat-label\">Registered Courses</div>\n");
      out.write("              <div class=\"stat-detail\">Total Credits: <strong>");
      out.print( totalCredits );
      out.write(" Units</strong></div>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <ul class=\"schedule-list\">\n");
      out.write("              ");
 for(Enrollment e : myEnrollments) { 
                  Course c = courseDAO.getCourseById(e.getCourseId());
                  String schedule = (c != null) ? c.getSchedule() : "N/A";
              
      out.write("\n");
      out.write("                <li class=\"schedule-item\">\n");
      out.write("                  <div class=\"schedule-item-info\">\n");
      out.write("                    <span class=\"schedule-course-title\">");
      out.print( e.getCourseName() );
      out.write("</span>\n");
      out.write("                    <span class=\"schedule-course-time\">🕒 ");
      out.print( schedule );
      out.write("</span>\n");
      out.write("                  </div>\n");
      out.write("                  <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/student/enroll\" method=\"post\" class=\"schedule-drop-form\">\n");
      out.write("                    <input type=\"hidden\" name=\"courseId\" value=\"");
      out.print( e.getCourseId() );
      out.write("\"/>\n");
      out.write("                    <input type=\"hidden\" name=\"action\" value=\"drop\"/>\n");
      out.write("                    <button type=\"submit\" class=\"btn-icon-danger\" title=\"Drop Course\" aria-label=\"Drop ");
      out.print( e.getCourseName() );
      out.write("\">\n");
      out.write("                      ✕\n");
      out.write("                    </button>\n");
      out.write("                  </form>\n");
      out.write("                </li>\n");
      out.write("              ");
 } 
      out.write("\n");
      out.write("            </ul>\n");
      out.write("          ");
 } else { 
      out.write("\n");
      out.write("            <div class=\"empty-schedule-state\">\n");
      out.write("              <span class=\"empty-icon\" aria-hidden=\"true\">📅</span>\n");
      out.write("              <p>No active registrations.</p>\n");
      out.write("              <p class=\"subtext\">Select a course and click \"Register Course\" to begin.</p>\n");
      out.write("            </div>\n");
      out.write("          ");
 } 
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </aside>\n");
      out.write("    </div>\n");
      out.write("  </main>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
